define([
	"skylark-jsbin-coder",
	"./jsbin",
    "./chrome/font",
    "./chrome/analytics",
    "./chrome/settings",
    "./render/saved-history-preview",
    "./chrome/esc",
    "./chrome/share",
    "./chrome/issue",
    "./chrome/download",
    "./chrome/login",
    "./chrome/tips",
    "./chrome/keys",
    "./chrome/save",
    "./chrome/navigation",
    "./chrome/file-drop",
    "./chrome/gist",
    "./chrome/spinner",
    "./chrome/infocard",
    "./chrome/last-bin",
    "./chrome/archive",
    "./chrome/transfer",
    "./chrome/welcome-panel",
    "./chrome/help-search",
    "./chrome/app"

],function(coder,jsbin){
	return jsbin;
});